# Generated by Django 5.1.5 on 2025-02-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_memberprofilerole', '0003_orgadmin_projectadmin_siteadmin_memberprofilerole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadmin',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_admin_roles', to='app_memberprofilerole.member'),
        ),
    ]
