# Generated by Django 5.0.3 on 2024-10-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0017_rename_siterole_siteorgrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemembership',
            old_name='site_role',
            new_name='org_role',
        ),
    ]
