# Generated by Django 5.0.3 on 2024-10-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0019_organizationdetail_roadmapitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdetail',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_organizationdetail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_roadmap_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
