# Generated by Django 5.0.3 on 2024-10-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0022_projectdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='app_organization.project'),
        ),
    ]
