# Generated by Django 5.0.3 on 2024-10-12 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0023_alter_projectdetail_pro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectroadmap',
            name='org',
        ),
        migrations.RemoveField(
            model_name='projectroadmap',
            name='project',
        ),
        migrations.AddField(
            model_name='projectroadmap',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_roadmaps', to='app_organization.project'),
        ),
        migrations.AlterField(
            model_name='projectroadmap',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_project_roadmaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
