# Generated by Django 5.0.3 on 2024-10-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0024_remove_projectroadmap_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectroadmap',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_roadmap_items', to='app_organization.project'),
        ),
    ]
