# Generated by Django 5.0.3 on 2024-10-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0025_alter_projectroadmap_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_project_details', to='app_organization.organization'),
        ),
    ]
