# Generated by Django 5.0.3 on 2024-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0028_projecttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttemplate',
            name='text',
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
