# Generated by Django 5.0.3 on 2024-11-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0029_remove_projecttemplate_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_template_details', to='app_organization.projecttemplate'),
        ),
    ]
