# Generated by Django 5.0.3 on 2024-11-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0030_projectdetail_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='est_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='total_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
