# Generated by Django 5.0.3 on 2024-11-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0031_projectdetail_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadministration',
            name='project_state',
            field=models.CharField(choices=[('Initiation', 'Initiation'), ('Started', 'Started'), ('Launched', 'Launched'), ('Archived', 'Archived')], default='Initiation', max_length=255),
        ),
    ]
