# Generated by Django 5.0.3 on 2024-11-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0033_devvaluestream_opsvaluestream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devvaluestream',
            name='org',
        ),
        migrations.AddField(
            model_name='devvaluestream',
            name='ops',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ops_dev_value_streams', to='app_organization.opsvaluestream'),
        ),
    ]
