# Generated by Django 5.0.3 on 2024-11-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0036_devvaluestreamstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestream',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev_value_stream_project', to='app_organization.project'),
        ),
    ]
