# Generated by Django 5.0.3 on 2024-11-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0039_devvaluestreamstep_delay_devvaluestreamstep_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsvaluestreamstep',
            name='delay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opsvaluestreamstep',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
