# Generated by Django 5.0.3 on 2024-11-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0040_opsvaluestreamstep_delay_opsvaluestreamstep_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestreamstep',
            name='supporting_ops_steps',
            field=models.ManyToManyField(blank=True, related_name='supported_by_dev_steps', to='app_organization.opsvaluestreamstep'),
        ),
    ]
