# Generated by Django 5.0.3 on 2024-11-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0042_remove_devvaluestreamstep_supporting_ops_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestream',
            name='trigger',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='devvaluestream',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='trigger',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
