# Generated by Django 5.0.3 on 2024-11-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0050_imagemap_imagemaparea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='folder_image_maps/'),
        ),
    ]
