# Generated by Django 5.0.3 on 2024-11-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0051_alter_imagemap_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemaparea',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='blocked_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='position',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
