# Generated by Django 5.0.3 on 2024-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0052_alter_imagemaparea_options_imagemaparea_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestream',
            name='percentage_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='opsvaluestreamstep',
            name='percentage_accuracy',
            field=models.FloatField(default=0),
        ),
    ]
