# Generated by Django 5.0.3 on 2024-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0053_devvaluestream_percentage_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsvaluestream',
            name='delay_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='efficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='percentage_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opsvaluestream',
            name='value_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
