# Generated by Django 5.0.3 on 2024-11-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0054_opsvaluestream_delay_time_opsvaluestream_efficiency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opsvaluestream',
            old_name='percentage_accuracy',
            new_name='rolled_percentage_avg',
        ),
    ]
