# Generated by Django 5.0.3 on 2024-11-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0055_rename_percentage_accuracy_opsvaluestream_rolled_percentage_avg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devvaluestream',
            old_name='percentage_accuracy',
            new_name='efficiency',
        ),
        migrations.AddField(
            model_name='devvaluestream',
            name='delay_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devvaluestream',
            name='rolled_percentage_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='devvaluestream',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devvaluestream',
            name='value_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
