# Generated by Django 5.0.3 on 2024-11-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0056_rename_percentage_accuracy_devvaluestream_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devvaluestreamstep',
            name='percentage_accuracy',
            field=models.FloatField(default=0),
        ),
    ]
