# Generated by Django 5.0.3 on 2024-11-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0057_devvaluestreamstep_percentage_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemap',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemap',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
