# Generated by Django 5.0.3 on 2024-11-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0062_remove_iteration_text_iteration_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='iteration_length',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
