# Generated by Django 5.0.3 on 2024-11-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0064_remove_release_text_release_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_length',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
