# Generated by Django 5.0.3 on 2024-11-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0067_remove_workflow_pro_workflow_wor_projectworkflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='wor',
        ),
        migrations.AddField(
            model_name='workflow',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_work_flows', to='app_organization.organization'),
        ),
    ]
