# Generated by Django 5.0.3 on 2024-11-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0071_orgmetric_orgrelease_orgteam_orgworkflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgrelease',
            name='text',
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='apply_release_iteration_length',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='est_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='release_length',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='total_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
