# Generated by Django 5.0.3 on 2024-11-26 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0072_remove_orgrelease_text_orgrelease_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_iterations', to='app_organization.release'),
        ),
    ]
