# Generated by Django 5.0.3 on 2024-11-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0077_orgiterationx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgIterationx',
        ),
    ]
