# Generated by Django 5.0.3 on 2024-11-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0082_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
