# Generated by Django 5.0.3 on 2024-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0084_orgimagemap_display_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemaparea',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagemaparea',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
