# Generated by Django 5.0.3 on 2024-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0087_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgimagemap',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='folder_image_maps/thumbnails/'),
        ),
    ]
