# Generated by Django 5.0.3 on 2024-11-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0088_orgimagemap_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgimagemap',
            name='thumbnail',
        ),
    ]
