# Generated by Django 5.0.3 on 2024-11-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0089_remove_orgimagemap_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='default_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
