# Generated by Django 5.0.3 on 2024-11-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0090_framework_content_framework_default_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='public_framework',
            field=models.BooleanField(default=False),
        ),
    ]
