# Generated by Django 5.0.3 on 2024-12-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0094_impactmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactmapping',
            name='orgmapping',
        ),
        migrations.AddField(
            model_name='impactmapping',
            name='org_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_mapping_impact_mappings', to='app_organization.orgmapping'),
        ),
    ]
