# Generated by Django 5.0.3 on 2024-12-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0096_remove_impactmapping_org_mapping_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgMapping',
        ),
    ]
