# Generated by Django 5.0.3 on 2024-12-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0097_delete_orgmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmapping',
            name='node_type',
            field=models.CharField(blank=True, choices=[('Goal', 'Goal'), ('Actor', 'Actor'), ('Impact', 'Impact'), ('Deliverable', 'Deliverable'), ('Task', 'Task')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='impactmapping',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_organization.impactmapping'),
        ),
    ]
