# Generated by Django 5.0.3 on 2024-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0101_alter_impactmap_name_alter_impactmap_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmap',
            name='link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
