# Generated by Django 5.0.3 on 2024-12-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0103_persona_activity_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('est_duration', models.PositiveIntegerField(default=0)),
                ('total_duration', models.PositiveIntegerField(default=0)),
                ('story_id', models.PositiveIntegerField()),
                ('release_id', models.PositiveIntegerField()),
                ('iteration_id', models.PositiveIntegerField()),
                ('activity_id', models.PositiveIntegerField()),
                ('step_id', models.PositiveIntegerField()),
                ('persona_id', models.PositiveIntegerField()),
                ('mapped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Story Mapping',
                'verbose_name_plural': 'Story Mappings',
                'unique_together': {('story_id', 'release_id', 'iteration_id', 'activity_id', 'step_id', 'persona_id')},
            },
        ),
    ]
