# Generated by Django 5.0.3 on 2024-12-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0104_storymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymapping',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_story_mappings', to='app_organization.project'),
        ),
    ]
