# Generated by Django 5.0.3 on 2024-12-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0105_storymapping_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymapping',
            name='story_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
