# Generated by Django 5.0.3 on 2024-12-07 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0109_alter_storymapping_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storymapping',
            unique_together={('story_id',)},
        ),
    ]
