# Generated by Django 5.0.3 on 2024-12-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0111_persona_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_backlogs', to='app_organization.persona'),
        ),
    ]
