# Generated by Django 5.0.3 on 2024-12-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0113_alter_storymapping_iteration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymapping',
            name='iteration_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
