# Generated by Django 5.0.3 on 2024-12-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0120_backlog_priority_alter_backlog_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='owner',
        ),
        migrations.AddField(
            model_name='backlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backlog',
            name='pulled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb_pulled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtasks',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
