# Generated by Django 5.0.3 on 2024-12-15 08:06

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0121_remove_backlog_owner_backlog_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlog',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AddField(
            model_name='backlog',
            name='connected_to_hierarchy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='connected_to_hierarchy_id',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tree', to='app_organization.backlog'),
        ),
    ]
