# Generated by Django 5.0.3 on 2024-12-15 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0124_backlog_collection'),
        ('app_organization', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgboard',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_project_boards', to='app_organization.project'),
        ),
        migrations.AlterField(
            model_name='orgboard',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_boards', to='app_organization.organization'),
        ),
    ]
