# Generated by Django 5.0.3 on 2024-12-16 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0127_projectboardstatetransition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectBoardColumn',
        ),
    ]
