# Generated by Django 5.0.3 on 2024-12-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0128_delete_projectboardcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboardstate',
            name='wip_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
