# Generated by Django 5.0.3 on 2024-12-16 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0129_projectboardstate_wip_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboardstatetransition',
            name='from_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='app_organization.projectboardstate'),
        ),
        migrations.AlterField(
            model_name='projectboardstatetransition',
            name='to_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_to', to='app_organization.projectboardstate'),
        ),
    ]
