# Generated by Django 5.0.3 on 2024-12-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0132_projectboardcolumn_projectboardstatetransition_card_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectBoardColumn',
        ),
    ]
