# Generated by Django 5.0.3 on 2024-12-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0136_alter_projectboardcard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboardcard',
            name='backlog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_cards', to='app_organization.backlog'),
        ),
        migrations.AlterField(
            model_name='projectboardcard',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_cards', to='app_organization.projectboard'),
        ),
        migrations.AlterField(
            model_name='projectboardcard',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_cards', to='app_organization.projectboardstate'),
        ),
    ]
