# Generated by Django 5.0.3 on 2024-12-18 06:35

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0137_alter_projectboardcard_backlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_organization.backlog'),
        ),
    ]
