# Generated by Django 5.0.3 on 2024-12-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0138_alter_backlog_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_organization.backlogtype'),
        ),
    ]
