# Generated by Django 5.0.3 on 2024-12-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0139_alter_backlogtype_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymapping',
            name='backlog_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_ref', to='app_organization.backlog'),
        ),
    ]
