# Generated by Django 5.0.3 on 2024-12-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0140_storymapping_backlog_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
