# Generated by Django 5.0.3 on 2024-12-22 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0141_backlog_end_date_backlog_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='progress',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
