# Generated by Django 5.0.3 on 2024-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0142_backlog_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrelease',
            name='no_of_iterations',
            field=models.IntegerField(default=5),
        ),
    ]
