# Generated by Django 5.0.3 on 2024-12-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0145_alter_projectroadmap_status_orgpracticeevent'),
        ('app_organization', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgevent',
            name='project_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_template_org_events', to='app_organization.projecttemplate'),
        ),
    ]
