# Generated by Django 5.0.3 on 2024-12-24 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0146_orgevent_project_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgpracticeevent',
            name='text',
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='est_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='event_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='event_facilitation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='event_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_owner_org_practice_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgpracticeevent',
            name='total_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
