# Generated by Django 5.0.3 on 2024-12-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0147_remove_orgpracticeevent_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrelease',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
