# Generated by Django 5.0.3 on 2024-12-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0148_orgrelease_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgiteration',
            name='iteration_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgiteration',
            name='quarter',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='quarter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orgrelease',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
