# Generated by Django 5.0.3 on 2024-12-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0149_orgiteration_iteration_number_orgiteration_quarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgiteration',
            name='iteration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgiteration',
            name='iteration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='release_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='release_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
