# Generated by Django 5.0.3 on 2024-12-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0150_orgiteration_iteration_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgiteration',
            name='end_day',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orgiteration',
            name='start_day',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
