# Generated by Django 5.0.3 on 2024-12-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0151_orgiteration_end_day_orgiteration_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgiteration',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
