# Generated by Django 5.0.3 on 2024-12-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0152_orgiteration_version_orgrelease_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgiteration',
            name='major_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
