# Generated by Django 5.0.3 on 2024-12-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0153_orgiteration_major_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrelease',
            name='release_official_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
