# Generated by Django 5.0.3 on 2024-12-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0155_orgrelease_major_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgiteration',
            name='major_version',
        ),
    ]
