# Generated by Django 5.0.3 on 2024-12-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0156_remove_orgiteration_major_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgiteration',
            name='build_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
