# Generated by Django 5.0.3 on 2024-12-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0160_orgiteration_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectroadmap',
            name='roadmap_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
