# Generated by Django 5.0.3 on 2024-12-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0161_projectroadmap_roadmap_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='business_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='ops_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='tech_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReadyDoneFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('est_duration', models.PositiveIntegerField(default=0)),
                ('total_duration', models.PositiveIntegerField(default=0)),
                ('business_ready', models.BooleanField(default=False)),
                ('tech_ready', models.BooleanField(default=False)),
                ('qa_ready', models.BooleanField(default=False)),
                ('ops_ready', models.BooleanField(default=False)),
                ('business_done', models.BooleanField(default=False)),
                ('tech_done', models.BooleanField(default=False)),
                ('qa_done', models.BooleanField(default=False)),
                ('ops_done', models.BooleanField(default=False)),
                ('all_ready', models.BooleanField(default=False)),
                ('all_done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('backlog_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_organization.backlog')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
