# Generated by Django 5.0.3 on 2024-12-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0163_remove_backlog_business_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_release_mapped_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_release_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
