# Generated by Django 5.0.3 on 2024-12-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0165_project_project_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_iterations', to='app_organization.orgiteration'),
        ),
    ]
