# Generated by Django 5.0.3 on 2025-01-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0167_backlog_committed_to_iteration_projectiteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgiteration',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='test_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgrelease',
            name='release_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgrelease',
            name='release_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
