# Generated by Django 5.0.3 on 2025-01-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0168_orgiteration_timestamp_orgrelease_test_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrelease',
            name='iteration_length_in_mins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgrelease',
            name='release_length_in_mins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
