# Generated by Django 5.0.3 on 2025-01-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0169_orgrelease_iteration_length_in_mins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgiteration',
            name='iteration_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgiteration',
            name='iteration_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
