# Generated by Django 5.0.3 on 2025-01-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0170_alter_orgiteration_iteration_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboardcard',
            name='org_iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_iteration_cards', to='app_organization.orgiteration'),
        ),
        migrations.AddField(
            model_name='projectboardcard',
            name='org_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_release_cards', to='app_organization.orgrelease'),
        ),
    ]
