# Generated by Django 5.0.3 on 2025-01-11 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0171_projectboardcard_org_iteration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectboardcard',
            name='org_iteration',
        ),
        migrations.RemoveField(
            model_name='projectboardcard',
            name='org_release',
        ),
        migrations.AddField(
            model_name='projectboard',
            name='org_iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_iteration_boards', to='app_organization.orgiteration'),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='org_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_release_boards', to='app_organization.orgrelease'),
        ),
    ]
