# Generated by Django 5.0.3 on 2025-01-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0172_remove_projectboardcard_org_iteration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgiteration',
            name='done_story_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgiteration',
            name='total_story_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
