# Generated by Django 5.1.5 on 2025-02-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0173_orgiteration_done_story_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='app_organization.project'),
        ),
        migrations.AlterField(
            model_name='orgrelease',
            name='predecessors',
            field=models.ManyToManyField(blank=True, to='app_organization.orgrelease'),
        ),
        migrations.AlterField(
            model_name='projectadministration',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_administrations', to='app_organization.project'),
        ),
    ]
