# Generated by Django 5.1.5 on 2025-02-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0174_projectrole_project_alter_orgrelease_predecessors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='app_organization.project'),
        ),
    ]
