# Generated by Django 5.1.5 on 2025-02-10 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0175_projecttemplate_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='pro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='app_organization.project'),
        ),
    ]
