# Generated by Django 5.1.5 on 2025-02-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0177_backlog_acceptance_critera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='acceptance_critera',
            new_name='acceptance_criteria',
        ),
    ]
