# Generated by Django 5.1.5 on 2025-03-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0180_projectworkflowstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkflow',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_workflows', to='app_organization.project'),
        ),
    ]
