# Generated by Django 5.1.5 on 2025-03-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0181_projectworkflow_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectworkflow',
            name='organization',
        ),
        migrations.AlterField(
            model_name='projectworkflow',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_project_workflows', to='app_organization.project'),
        ),
    ]
