# Generated by Django 5.1.5 on 2025-03-02 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0182_remove_projectworkflow_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='project_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_workflow', to='app_organization.projectworkflow'),
        ),
    ]
