# Generated by Django 5.1.5 on 2025-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0183_projectboard_project_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboardstate',
            name='buffer_column',
            field=models.BooleanField(default=False),
        ),
    ]
