# Generated by Django 5.1.5 on 2025-03-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0184_projectboardstate_buffer_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboardstate',
            name='column_type',
            field=models.CharField(choices=[('To Do', 'To Do'), ('WIP', 'WIP'), ('Done', 'Done')], default='To Do', max_length=10),
        ),
    ]
