# Generated by Django 5.1.5 on 2025-03-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0185_projectboardstate_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboardstate',
            name='default_board',
            field=models.BooleanField(default=False),
        ),
    ]
