# Generated by Django 5.1.5 on 2025-03-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0186_projectboardstate_default_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectboardstate',
            name='default_board',
        ),
        migrations.AddField(
            model_name='projectboard',
            name='default_board',
            field=models.BooleanField(default=False),
        ),
    ]
