# Generated by Django 5.1.5 on 2025-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0188_boardcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcard',
            name='display_card_aging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_assignee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_due_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_iteration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_priority',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_size',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_type',
            field=models.BooleanField(default=False),
        ),
    ]
