# Generated by Django 5.1.5 on 2025-03-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0189_boardcard_display_card_aging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcard',
            name='project_board',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_board_board_cards', to='app_organization.projectboard'),
        ),
    ]
