# Generated by Django 5.1.5 on 2025-03-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0190_alter_boardcard_project_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcard',
            name='display_card_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcard',
            name='display_card_done',
            field=models.BooleanField(default=False),
        ),
    ]
