# Generated by Django 5.1.5 on 2025-03-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0191_boardcard_display_card_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='board_type',
            field=models.CharField(choices=[('TODO_WIP_DONE', 'To Do, WIP, Done'), ('KANBAN', 'Kanban'), ('SCRUM', 'To Do, WIP, Done'), ('Portfolio', 'Portfolio'), ('Program', 'Program'), ('Project', 'Project')], default='TODO_WIP_DONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectboardstate',
            name='column_type',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('WIP', 'WIP'), ('Done', 'Done')], default='ToDo', max_length=10),
        ),
    ]
