# Generated by Django 5.1.5 on 2025-03-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0192_projectboard_board_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectboard',
            name='project_workflow',
        ),
        migrations.AddField(
            model_name='backlog',
            name='board_swimlane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_swimlane', to='app_organization.projectboardswimlane'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='connected_to_hierarchy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tree', to='app_organization.backlog'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_organization.backlog'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_types', to='app_organization.backlogtype'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='board_type',
            field=models.CharField(choices=[('TODO_WIP_DONE', 'To Do, WIP, Done'), ('KANBAN', 'To Do, Doing, Done'), ('SCRUM', 'To Do, WIP, Done'), ('Portfolio', 'Portfolio'), ('Program', 'Program'), ('Project', 'Project')], default='TODO_WIP_DONE', max_length=50),
        ),
    ]
