# Generated by Django 5.1.5 on 2025-03-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0193_remove_projectboard_project_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboardstate',
            name='apply_wip_limit',
            field=models.BooleanField(default=True),
        ),
    ]
