# Generated by Django 5.1.5 on 2025-03-06 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0195_projectboardcard_substate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboardstatetransition',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_transitions', to='app_organization.projectboard'),
        ),
    ]
