# Generated by Django 5.1.5 on 2025-03-07 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0198_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='to_state',
        ),
        migrations.AddField(
            model_name='movement',
            name='from_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_froms', to='app_organization.projectboardstate'),
        ),
        migrations.AddField(
            model_name='movement',
            name='to_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_tos', to='app_organization.projectboardstate'),
        ),
        migrations.AddField(
            model_name='movement',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
