# Generated by Django 5.1.5 on 2025-03-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0200_movement_date_movement_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboardstatetransition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectboardstatetransition',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
