# Generated by Django 5.1.5 on 2025-03-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0201_projectboardstatetransition_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectboardstatetransition',
            old_name='date',
            new_name='date_field',
        ),
        migrations.RenameField(
            model_name='projectboardstatetransition',
            old_name='time',
            new_name='time_field',
        ),
    ]
