# Generated by Django 5.0.3 on 2024-11-30 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField(max_length=2048)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
