# Generated by Django 5.0.3 on 2024-10-09 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0011_memberrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='member_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_organization.memberrole'),
        ),
    ]
