# Generated by Django 5.0.3 on 2024-10-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0002_projectrole_projectmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='text',
        ),
    ]
