# Generated by Django 5.0.3 on 2024-10-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0003_remove_projectmembership_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrole',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='role_name',
        ),
        migrations.AddField(
            model_name='projectrole',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
