# Generated by Django 5.0.3 on 2024-10-09 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_memberprofilerole', '0001_initial'),
        ('app_organization', '0008_team_members_team_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrole',
            name='test_field',
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_organization.team'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='role_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Viewer', 'Viewer'), ('NoView', 'No View')], default='NoView', max_length=255),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_memberprofilerole.member')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_organization.team')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
