# Generated by Django 5.0.3 on 2024-10-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0013_backlogsupertype_backlogtype_backlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='org',
        ),
        migrations.RemoveField(
            model_name='backlogsupertype',
            name='org',
        ),
        migrations.RemoveField(
            model_name='backlogtype',
            name='org',
        ),
        migrations.AddField(
            model_name='backlog',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlogs', to='app_organization.project'),
        ),
        migrations.AddField(
            model_name='backlogsupertype',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlog_super_type_supertypes', to='app_organization.project'),
        ),
        migrations.AddField(
            model_name='backlogtype',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlog_type_types', to='app_organization.project'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='app_organization.backlog'),
        ),
    ]
