# Generated by Django 5.0.3 on 2024-11-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0081_oldimagemaparea_orgimagemap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldimagemaparea',
            name='image_map',
        ),
        migrations.DeleteModel(
            name='ImageMap',
        ),
        migrations.DeleteModel(
            name='OldImageMapArea',
        ),
    ]
