# Generated by Django 5.0.3 on 2024-11-26 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0083_imagemap_alter_imagemaparea_image_map_imagemaparea1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgImageMap1',
            new_name='OrgImageMap',
        ),
    ]
